import bcrypt from 'bcryptjs'
const PLACEHOLDER_IMAGE = 'https://via.placeholder.com/600x400?text=No+Image+Available';
const data = {
  users: [
    {
      name: 'mohit',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Vikash',
      email: 'cust@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
    {
      name: "Saif",
      email: "mohammadsaif0847@gmail.com",
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    }
  ],

  products: [
    {
      name: 'Mini Cooper SE',
      type: 'NEW',
      brand: 'MINI',
      year: 2024,
      variant: [
        {
          name: 'SE Signature',
          model: 'Cooper SE',
          fuelType: 'ELECTRIC',
          transmission: 'AUTOMATIC',
          features: ['Sunroof', 'Apple CarPlay', 'Leather Seats'],
          exShowroomPrice: 3000000,
          TCS: 30000,
          insurance: 45000,
          roadtax: 55000,
          onroadPrice: 3600000,
          discount: 100000,
          onroadAfterDiscount: 0,
        },
      ],
      avilableColors: ['White', 'Yellow', 'Black'],
      slug: 'mini-cooper-se',
      category: 'Hatchback',
      image: '/Car photo/verna.jpg',
      rating: 4.7,
      numReviews: 13,
      countInStock: 5,
      description: 'Electric hatchback with iconic Mini design and premium features.',
      isFeatured: true,
      banner: PLACEHOLDER_IMAGE,
    },
    {
      name: 'Mini Countryman Cooper S',
      type: 'NEW',
      brand: 'MINI',
      year: 2024,
      variant: [
        {
          name: 'Cooper S Classic',
          model: 'Countryman',
          fuelType: 'PETROL',
          transmission: 'AUTOMATIC',
          features: ['Panoramic Sunroof', 'Navigation', 'Ambient Lighting'],
          exShowroomPrice: 3900000,
          insurance: 55000,
          TCS: 39000,
          roadtax: 65000,
          onroadPrice: 4600000,
          discount: 150000,
          onroadAfterDiscount: 0,
        },
        {
          name: 'Cooper S Iconic',
          model: 'Countryman',
          fuelType: 'PETROL',
          transmission: 'DCT',
          features: ['Wireless Charging', 'Premium Audio', 'Heads-Up Display'],
          exShowroomPrice: 4200000,
          TCS: 42000,
          insurance: 60000,
          roadtax: 70000,
          onroadPrice: 4950000,
          discount: 120000,
          onroadAfterDiscount: 0,
        },
        {
          name: 'Cooper S All4',
          model: 'Countryman',
          fuelType: 'PETROL',
          transmission: 'AUTOMATIC',
          features: ['All Wheel Drive', 'Adaptive Cruise', 'Parking Assist'],
          exShowroomPrice: 4500000,
          TCS: 45000,
          insurance: 65000,
          roadtax: 75000,
          onroadPrice: 5200000,
          discount: 170000,
          onroadAfterDiscount: 0,
        },],
      avilableColors: ['Red', 'Blue', 'Green'],
      slug: 'mini-countryman-cooper-s',
      category: 'SUV',
      image: '/Car photo/verna.jpg',
      rating: 4.5,
      numReviews: 22,
      countInStock: 4,
      description: 'The Mini Countryman Cooper S is a spacious and sporty compact SUV.',
      isFeatured: false,
      banner: PLACEHOLDER_IMAGE,
    },
    {
      name: 'Mini 3-Door Hatch JCW',
      type: 'USED',
      brand: 'MINI',
      year: 2022,
      variant: [
        {
          name: 'JCW',
          model: '3-Door Hatch',
          fuelType: 'PETROL',
          transmission: 'MANUAL',
          features: ['Sport Exhaust', 'HUD', '18-inch Alloys'],
          originalPrice: 3700000,
          insurance: 40000,
          roadtax: 50000,
          totalTrip: 3000,
          onroadPrice: 4300000,
          discount: 300000,
          onroadAfterDiscount: 0,
        },
      ],
      avilableColors: ['Black', 'Red'],
      slug: 'mini-jcw-3-door',
      category: 'Hatchback',
      image: '/Car photo/verna.jpg',
      rating: 4.8,
      numReviews: 30,
      countInStock: 2,
      description: 'High-performance John Cooper Works variant with aggressive design and handling.',
      isFeatured: true,
      banner: PLACEHOLDER_IMAGE,
    },
    {
      name: 'Mini Convertible Cooper',
      type: 'USED',
      brand: 'MINI',
      year: 2021,
      variant: [
        {
          name: 'Convertible Cooper',
          model: 'Convertible',
          fuelType: 'PETROL',
          transmission: 'AUTOMATIC',
          features: ['Convertible Roof', 'Heated Seats', 'LED Headlamps'],
          originalPrice: 3600000,
          insurance: 38000,
          roadtax: 45000,
          onroadPrice: 4100000,
          discount: 200000,
          onroadAfterDiscount: 0,
          totalTrip: 10000,
        },
      ],
      avilableColors: ['Blue', 'White'],
      slug: 'mini-convertible-cooper',
      category: 'Convertible',
      image: '/Car photo/verna.jpg',
      rating: 4.6,
      numReviews: 18,
      countInStock: 3,
      description: 'Enjoy open-top freedom with Mini’s iconic styling and fun-to-drive attitude.',
      isFeatured: false,
      banner: PLACEHOLDER_IMAGE,
    },
  ]

}

export default data
